#!/bin/sh

. ./common
 
echo "Clearing fixtures and creating timed files..."
cd fixtures || exit
rm a b c
touch old
sleep 1
touch mid
sleep 1
touch new
cd .. || exit
sleep 1

Mount --sort-dirents=yes --reverse-dirents=no --sort-by-ctime=yes
Expect oldmidnew
Unmount

Mount --sort-dirents=yes --reverse-dirents=yes --sort-by-ctime=yes
Expect newmidold
Unmount

echo "Recreating a,b,c testfiles..."
cd fixtures || exit
rm old mid new
touch a b c
cd .. || exit
