#!/bin/sh

. ./common
 
echo "Clearing timed directory and creating timed files..."
rm -r ./timed
mkdir timed
cd timed || exit
touch old
sleep 1
touch mid
sleep 1
touch new
cd .. || exit

Mount -m --sort-dirents=yes --reverse-dirents=no --sort-by-ctime=yes
Expect oldmidnew
Unmount

Mount -m --sort-dirents=yes --reverse-dirents=yes --sort-by-ctime=yes
Expect newmidold
Unmount
